

var words = ['surf','surfing','blowing up','blow tail','shred','shredded','heavy','finner','rad','radical','hack','hackathon don','chuncky','blown out','off-shore','side-shore','section','air section','wind conditions','crumbly lip','air drop','free fall','slab','frothing','lil ripper','heavy section','closed out','shaka','with the boys','bowl','tide switch','bottomed out','pearled','air reverse','mad full air reverse','full rotation','slob','blow tail','cutties','floater','down the line','mental','Dane turns','Kelly Slater','Nat Young','Gold Coast','vertical','pipeline','spit','sand bar','reef break','feathered lip','goin’ mad','pig dog','drop knee','wax the stick','freshie','fresh stick','Firing','over it','done','crippling shorebreak','white water','duck diving','ice cream head aches','kook','too many kooks','FUCKING kooks','beat it kook','you ain’t local','loc dawg','king of the peak','split the peak','round house cut back','insane, technical maneuvers','marine layer','capped out','good day to stay in','glass','hot glass','rip','rip tide','dry hair paddle out','SUP free surf zone','longboard','shortboard','funboard','utility board','alley-oop','stale','stale-fish','backside air reverse','backside full rote.','full rote','huge full rote.','Jordy Smith','hollow','Mick Fanning','slide 5','hang 5','hang 10','wax','coffee','wetsuit tan','Ocean Beach','the OB','nutty','best section','barreling','leash','tomb-stoning','fighting for the peak','wave of my life','wave of the winter','shaping up the bar','turning on','frothy top','foam climb','making the section','nose pick','mind surfing','Dane','Kelly','Slates','Mitch','Joel','Parko','Freddy P.','Santa Cruz','East Side','West Side','North Jetty','beat it kook','legend','he is a legend','Eddie would go','duck diving','courdoroy','swell','waves','period','feet','overhead','knee high','triple overhead','double over head','mellow','jumbled','cranking','fins free','backdooring','doggy door','standing tall','made the drop','bottom turn','bottom turn set up','poor-fair','fair','fair-good','EPIC','waves for everyone','line up','steeze','so easy','pitted','so pitted','soft lip','feathering lip','dawn patrol','blonde rigs','fan a spray','great paddler','unreal water man','WQS','WCT','WQS qualifiers','ridin’ the foamball','spitting wedgies','spitting pipe','pipe 3rd reef burner','claimin','gumby arms','barn dog','barn dog kook get lost','kook that left','power hack','Ano Nuevo? No thanks man','fickle little left','sketchy reef break','steezed','steezus','brobrasourous','floater','heat','freesurf','Jay Davies','Taj','Mick','Nat','John John','West Oz','backdoor it','Fiji','Teahupoo','zinc oxide','great day of waves','get the hair wet','schwack','hit','top turn','indy','rail grab','legend','waterman','kelp','fishy','fluked it'];
var phrases = ['Dane Fucking Reynolds','wedgey off the rocks','insane air sections','creased the stick','wetsuit smellin like a dead seal','I normally pull it when I wear booties','WAVES ARE FIRING','ITS FIRING OUT HERE, BRO','should have been here yesterday','should have been here 15 mins ago','you should have been here 45 mins ago','you got to get down to so-cal bro','once the tide switches its turning on','frothy top foam climb','you should’ve been here three days ago','been good everyday except today','da boys patrolling the line up','fins out',' so fucking pitted','big full round house cutty','I kinda hack’em','fuller shape and then we brought in the nose','should of ridden my four fin','thruster would have been the call today','super mellow so I surfed my fish','hadn’t surfed my fish in ages','poop stance to pig dog to switch foot, in and out, wave of the winter mother fucker','soo bad today man','it was SUPER FUN','nice lil hit of the top','just gonna go out and get some turns in','everyone pees in their wetsuit, right?','reeling right hand point break','grab a freshie','you seen my new 5 fin?','quivers on point','which board are you riding today?','you got any wax?','not in rhythm with the ocean','rhythm with the ocean','fantastic paddler','stroked into a late drop','chip-in','rows of white water','thress turns to the beach',' slabby sand bar','long period ground swell','so much positive energy in the water','texture on the wa','perfect air wind blowing back up the face','beers with the boys','sess’d for hours','you get my wave on your go pro','should of brough the gopro','its days like this why I surf','should of stayed in','I’m gonna suit up regardless','I just want to get wet','feels good just to get wet','getting back in the water','so grateful to just be out here','waves are shit','I’m surfing like shit','I need to work on my paddling technique','I’m thinking mavs next year','funnest lil nugs','A-frames for days'];


var output = $('#output');
var inputParagraphs = $('#paragraph-freq');
var headlineParagraphs = $('#headline-freq');

